services: 
  shopifyweb:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8080"  
    depends_on:
      - sqlserver
    env_file:
      - .env
    environment:
      - ConnectionStrings__DatabaseConnectionString=${ConnectionStrings__DatabaseConnectionString};
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P ${SA_PASSWORD} -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5